
CREATE TABLE IF NOT EXISTS public.advice
(
    id bigint NOT NULL DEFAULT nextval('advice_id_seq'::regclass),
    app_user_id bigint,
    status character varying(50) COLLATE pg_catalog."default",
    creation_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deadline timestamp without time zone,
    points integer,
    quiz_result character varying(50) COLLATE pg_catalog."default",
    movie_id bigint NOT NULL,
    CONSTRAINT advice_pkey PRIMARY KEY (id),
    CONSTRAINT advice_app_user_id_fkey FOREIGN KEY (app_user_id)
        REFERENCES public.app_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fkk57dftrufatgn7vkr0g78du5f FOREIGN KEY (movie_id)
        REFERENCES public.movie (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT advice_status_check CHECK (status::text = ANY (ARRAY['FAILED'::character varying, 'COMPLETED'::character varying, 'SKIPPED'::character varying, 'UNCOMPLETED'::character varying]::text[])),
    CONSTRAINT advice_quiz_result_check CHECK (quiz_result::text = ANY (ARRAY['FAILED'::character varying, 'SUCCEEDED'::character varying, 'UNCOMPLETED'::character varying]::text[]))
)


CREATE TABLE IF NOT EXISTS public.app_user
(
    age integer NOT NULL,
    points integer NOT NULL,
    streak integer NOT NULL,
    creation_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    goal_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(120) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT app_user_pkey PRIMARY KEY (id),
    CONSTRAINT app_user_goal_id_key UNIQUE (goal_id),
    CONSTRAINT app_user_username_key UNIQUE (username),
    CONSTRAINT fkdtoqpau366nv9egp2dwre4qxb FOREIGN KEY (goal_id)
        REFERENCES public.goal (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT app_user_role_check CHECK (role::text = ANY (ARRAY['USER'::character varying, 'ADMIN'::character varying]::text[]))
)


CREATE TABLE IF NOT EXISTS public.app_user_badge
(
    id integer NOT NULL DEFAULT nextval('app_user_badge_id_seq'::regclass),
    app_user_id bigint,
    badge_id bigint,
    CONSTRAINT app_user_badge_pkey PRIMARY KEY (id),
    CONSTRAINT app_user_badge_app_user_id_fkey FOREIGN KEY (app_user_id)
        REFERENCES public.app_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT app_user_badge_badge_id_fkey FOREIGN KEY (badge_id)
        REFERENCES public.badge (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)


CREATE TABLE IF NOT EXISTS public.app_user_course
(
    app_user_id bigint NOT NULL,
    course_id bigint NOT NULL,
    CONSTRAINT fk802a7wxm553ojeu4tx20cdhut FOREIGN KEY (app_user_id)
        REFERENCES public.app_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkihqlq88vsw6nkk5c95xumgjpu FOREIGN KEY (course_id)
        REFERENCES public.course (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)


CREATE TABLE IF NOT EXISTS public.app_user_lesson_progress
(
    completed_cards integer,
    progress real,
    app_user_id bigint NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    lesson_id bigint NOT NULL,
    quiz_result character varying(50) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'UNCOMPLETED'::character varying,
    CONSTRAINT app_user_lesson_progress_pkey PRIMARY KEY (id),
    CONSTRAINT fkbarj8v43mkifgim9cg9nbasxo FOREIGN KEY (lesson_id)
        REFERENCES public.lesson (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkijwqik4rny9837ci3770o5lu4 FOREIGN KEY (app_user_id)
        REFERENCES public.app_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT lesson_quiz_result_check CHECK (quiz_result::text = ANY (ARRAY['FAILED'::character varying::text, 'SUCCEEDED'::character varying::text, 'UNCOMPLETED'::character varying::text])),
    CONSTRAINT app_user_lesson_progress_status_check CHECK (status::text = ANY (ARRAY['UNCOMPLETED'::character varying, 'COMPLETED'::character varying, 'QUIZ_FAILED'::character varying]::text[]))
)


CREATE TABLE IF NOT EXISTS public.app_user_stats
(
    id bigint NOT NULL DEFAULT nextval('app_user_stats_id_seq'::regclass),
    app_user_id bigint,
    genre_id bigint NOT NULL,
    CONSTRAINT app_user_stats_pkey PRIMARY KEY (id),
    CONSTRAINT app_user_stats_app_user_id_fkey FOREIGN KEY (app_user_id)
        REFERENCES public.app_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT app_user_stats_genre_id_fkey FOREIGN KEY (genre_id)
        REFERENCES public.genre (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)


CREATE TABLE IF NOT EXISTS public.badge
(
    id bigint NOT NULL DEFAULT nextval('badge_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default",
    genre_to_unlock bigint,
    multiplier_level real DEFAULT 1.0,
    CONSTRAINT badge_pkey PRIMARY KEY (id),
    CONSTRAINT badge_genre_to_unlock_fkey FOREIGN KEY (genre_to_unlock)
        REFERENCES public.genre (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)


CREATE TABLE IF NOT EXISTS public.country_of_production
(
    country_code character varying(5) COLLATE pg_catalog."default",
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT country_of_production_pkey PRIMARY KEY (id)
)


CREATE TABLE IF NOT EXISTS public.course
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT course_pkey PRIMARY KEY (id)
)


CREATE TABLE IF NOT EXISTS public.genre
(
    id bigint NOT NULL DEFAULT nextval('genre_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default",
    tmdb_id bigint,
    CONSTRAINT genre_pkey PRIMARY KEY (id)
)


CREATE TABLE IF NOT EXISTS public.goal
(
    id bigint NOT NULL DEFAULT nextval('goal_id_seq'::regclass),
    time_to_dedicate real,
    min_year integer,
    type_id bigint,
    max_year integer,
    page integer,
    CONSTRAINT goal_pkey PRIMARY KEY (id),
    CONSTRAINT goal_type_id_fkey FOREIGN KEY (type_id)
        REFERENCES public.goal_type (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)


CREATE TABLE IF NOT EXISTS public.goal_country_of_production
(
    country_of_production_id bigint NOT NULL,
    goal_id bigint NOT NULL,
    CONSTRAINT fk7x3jkx9ou593c1r1sa4schrvi FOREIGN KEY (country_of_production_id)
        REFERENCES public.country_of_production (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.goal_genre
(
    genre_id bigint NOT NULL,
    goal_id bigint NOT NULL,
    CONSTRAINT fk5amokqhi8w8cclldvd7m7o9f FOREIGN KEY (genre_id)
        REFERENCES public.genre (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.goal_keyword
(
    goal_id bigint NOT NULL,
    keyword_id bigint NOT NULL,
    CONSTRAINT fkaugfpwjnu0qd458jakiec0ydy FOREIGN KEY (keyword_id)
        REFERENCES public.keyword (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
CREATE TABLE IF NOT EXISTS public.goal_theme
(
    id integer NOT NULL DEFAULT nextval('goal_theme_id_seq'::regclass),
    goal_id bigint,
    theme_id bigint,
    CONSTRAINT goal_theme_pkey PRIMARY KEY (id)
)


CREATE TABLE IF NOT EXISTS public.goal_type
(
    id bigint NOT NULL DEFAULT nextval('goal_type_id_seq'::regclass),
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT goal_type_pkey PRIMARY KEY (id),
    CONSTRAINT goal_type_type_key UNIQUE (type)
)

CREATE TABLE IF NOT EXISTS public.goal_type_course
(
    id integer NOT NULL DEFAULT nextval('goal_type_course_id_seq'::regclass),
    goal_type_id bigint,
    course_id bigint,
    CONSTRAINT goal_type_course_pkey PRIMARY KEY (id),
    CONSTRAINT goal_type_course_course_id_fkey FOREIGN KEY (course_id)
        REFERENCES public.course (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT goal_type_course_goal_type_id_fkey FOREIGN KEY (goal_type_id)
        REFERENCES public.goal_type (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)


CREATE TABLE IF NOT EXISTS public.image
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    base64_data text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT image_pkey PRIMARY KEY (id)
)


CREATE TABLE IF NOT EXISTS public.keyword
(
    tmdb_id integer,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT keyword_pkey PRIMARY KEY (id)
)


CREATE TABLE IF NOT EXISTS public.keyword_goal_entity_list
(
    keyword_entity_id bigint NOT NULL,
    goal_entity_list_id bigint NOT NULL,
    CONSTRAINT fkehfmraqdfq4tuokevtm0ksmb4 FOREIGN KEY (keyword_entity_id)
        REFERENCES public.keyword (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkrmbf08fhfjacjg08gg0tekmvn FOREIGN KEY (goal_entity_list_id)
        REFERENCES public.goal (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)


CREATE TABLE IF NOT EXISTS public.lesson
(
    id bigint NOT NULL DEFAULT nextval('lesson_id_seq'::regclass),
    course_id bigint,
    title character varying(255) COLLATE pg_catalog."default",
    content character varying(255) COLLATE pg_catalog."default",
    type character varying(50) COLLATE pg_catalog."default",
    lesson_order bigint,
    total_cards integer,
    CONSTRAINT lesson_pkey PRIMARY KEY (id),
    CONSTRAINT lesson_course_id_fkey FOREIGN KEY (course_id)
        REFERENCES public.course (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS public.lesson_image
(
    image_id bigint NOT NULL,
    lesson_id bigint NOT NULL,
    CONSTRAINT lesson_image_pkey PRIMARY KEY (image_id, lesson_id),
    CONSTRAINT fk2yca852nipbwuswui231l4wdn FOREIGN KEY (lesson_id)
        REFERENCES public.lesson (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk879vyx740k3t6xirmga05jqcb FOREIGN KEY (image_id)
        REFERENCES public.image (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.movie
(
    id bigint NOT NULL DEFAULT nextval('movie_id_seq'::regclass),
    overview character varying(800) COLLATE pg_catalog."default",
    original_language character varying(255) COLLATE pg_catalog."default",
    original_title character varying(400) COLLATE pg_catalog."default",
    title character varying(400) COLLATE pg_catalog."default",
    poster_path character varying(500) COLLATE pg_catalog."default",
    backdrop_path character varying(500) COLLATE pg_catalog."default",
    release_date date,
    tmdb_id bigint,
    CONSTRAINT movie_pkey PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS public.movie_genre
(
    movie_id bigint NOT NULL,
    genre_id bigint NOT NULL,
    CONSTRAINT fkp6vjabv2e2435at1hnuxg64yv FOREIGN KEY (movie_id)
        REFERENCES public.movie (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.quiz
(
    id bigint NOT NULL DEFAULT nextval('quiz_id_seq'::regclass),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    lesson_id bigint,
    advice_id bigint,
    question text COLLATE pg_catalog."default" NOT NULL,
    options text COLLATE pg_catalog."default",
    correct_option integer,
    correct_answer boolean,
    correct_order text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'UNCOMPLETED'::character varying,
    CONSTRAINT quiz_pkey PRIMARY KEY (id),
    CONSTRAINT fk_advice FOREIGN KEY (advice_id)
        REFERENCES public.advice (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fki10d7n4lf738sm3mon21aubik FOREIGN KEY (lesson_id)
        REFERENCES public.lesson (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT quiz_type_check CHECK (type::text = ANY (ARRAY['MULTIPLE_CHOICE'::character varying, 'TRUE_FALSE'::character varying, 'CHRONOLOGICAL_ORDER'::character varying]::text[])),
    CONSTRAINT chk_status CHECK (status::text = ANY (ARRAY['FAILED'::character varying, 'SUCCEEDED'::character varying, 'UNCOMPLETED'::character varying]::text[])),
    CONSTRAINT quiz_check CHECK (lesson_id IS NOT NULL OR advice_id IS NOT NULL),
    CONSTRAINT quiz_check1 CHECK (lesson_id IS NULL OR advice_id IS NULL),
    CONSTRAINT quiz_check2 CHECK (type::text = 'MULTIPLE_CHOICE'::text AND options IS NOT NULL AND correct_option IS NOT NULL AND correct_answer IS NULL AND correct_order IS NULL OR type::text = 'TRUE_FALSE'::text AND correct_answer IS NOT NULL AND options IS NULL AND correct_option IS NULL AND correct_order IS NULL OR type::text = 'CHRONOLOGICAL_ORDER'::text AND correct_order IS NOT NULL AND options IS NULL AND correct_option IS NULL AND correct_answer IS NULL)
)

CREATE TABLE IF NOT EXISTS public.theme
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default",
    tmdb_id integer,
    CONSTRAINT theme_pkey PRIMARY KEY (id)
)


CREATE TABLE IF NOT EXISTS public.token
(
    is_logged_out boolean,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint,
    access_token character varying(255) COLLATE pg_catalog."default",
    refresh_token character varying(255) COLLATE pg_catalog."default",
    reset_password_token character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT token_pkey PRIMARY KEY (id),
    CONSTRAINT fkebe1hlldfjpivnyt2tlydy4vl FOREIGN KEY (user_id)
        REFERENCES public.app_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)